apiVersion: v1
kind: Service
metada:
  name: client-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - port: 8080
      targetport: 8080
      #use only in development
      nodePort: 81515

