apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: web
      spec:
        containers:
          - name: jenkins
            image: mtinsonk/mtkproject2
            env:
              - name: JAVA_OPTS
                value: -Djenkins.install.runSetupWizard=false
            ports:
              - name: http-ports
                  containerPort: 8080
              - name: agent-port
                  contaninerPort: 50000