apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: mtinsonk/mtkproject2
        name: jenkins
        env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-ports
              containerPort: 8080
            - name: agent-port
              containerPort: 50000