apiVersion: v1
kind: Service
metada:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetport: 80
      #use only in development
      nodePort: 81516